sources:
  - name: raw
    schema: raw
    tables:
      - name: players
        config:
          freshness:
            warn_after: {count: 6, period: hour}
          loaded_at_field: _ingested_at
      - name: masteries
        config:
          freshness:
            warn_after: {count: 6, period: hour}
          loaded_at_field: _ingested_at