models:
  - name: players
    columns:
      - name: puuid
        tests: [not_null]
      - name: region
        tests:
          - not_null
          - accepted_values:
              values: ['BR1', 'EUN1', 'EUW1', 'LA1', 'LA2', 'NA1', 'OCE', 'OC1', 'RU1', 'RU', 'PH2', 'SG2', 'TH2', 'TR1', 'ME1', 'JP1', 'KR', 'SEA', 'TW2', 'VN2', 'PBE']
      - name: queueType
        tests:
          - not_null
          - accepted_values:
              values: ['RANKED_SOLO_5x5', 'RANKED_FLEX_SR', 'RANKED_FLEX_TT']
      - name: tier
        tests:
          - not_null
          - accepted_values:
              values: ['IRON', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'EMERALD', 'DIAMOND']
      - name: rank
        tests:
          - not_null
          - accepted_values:
              values: ['I', 'II', 'III', 'IV']
      - name: state_hash
        tests: [not_null]
      - name: _ingested_at
        tests: [not_null]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [puuid, state_hash]

  - name: masteries
    columns:
      - name: puuid
        tests: [not_null]
      - name: championId
        tests: [not_null]
      - name: region
        tests:
          - not_null
          - accepted_values:
              values: ['BR1', 'EUN1', 'EUW1', 'LA1', 'LA2', 'NA1', 'OCE', 'OC1', 'RU1', 'RU', 'PH2', 'SG2', 'TH2', 'TR1', 'ME1', 'JP1', 'KR', 'SEA', 'TW2', 'VN2', 'PBE']
      - name: state_hash
        tests: [not_null]
      - name: _ingested_at
        tests: [not_null]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [puuid, state_hash]