models:
  - name: players
    columns:
      - name: puuid
        tests: [not_null]
      - name: region
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['na1', 'euw1', 'eun1', 'br1', 'la1', 'la2', 'kr', 'jp1', 'ru', 'tr1', 'oc1', 'ph2', 'sg2', 'th2', 'tw2', 'vn2', 'me1', 'sea', 'pbe']
      - name: queueType
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['RANKED_SOLO_5x5', 'RANKED_FLEX_SR', 'RANKED_FLEX_TT']
      - name: tier
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['IRON', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'EMERALD', 'DIAMOND']
      - name: rank
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['I', 'II', 'III', 'IV']
      - name: state_hash
        tests: [not_null]
      - name: _ingested_at
        tests: [not_null]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [puuid, state_hash]

  - name: masteries
    columns:
      - name: puuid
        tests: [not_null]
      - name: championId
        tests: [not_null]
      - name: region
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['na1', 'euw1', 'eun1', 'br1', 'la1', 'la2', 'kr', 'jp1', 'ru', 'tr1', 'oc1', 'ph2', 'sg2', 'th2', 'tw2', 'vn2', 'me1', 'sea', 'pbe']
      - name: state_hash
        tests: [not_null]
      - name: _ingested_at
        tests: [not_null]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns: [puuid, state_hash]