models:
  - name: fct_players_champion_delta
    columns:
      - name: champion_delta_id
        tests: [not_null, unique]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments: {combination_of_columns: [puuid, champion_key, snapshot_date]}

  - name: dim_players_pool_profile_lifetime
    columns:
      - name: puuid
        tests: [not_null, unique]
