models:
  - name: silver_players
    columns:
      - name: puuid
        tests: [not_null, unique]
      - name: tier
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['IRON', 'BRONZE', 'SILVER', 'GOLD', 'PLATINUM', 'EMERALD', 'DIAMOND']
      - name: division
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments: {min_value: 1, max_value: 4}
      - name: total_games
        tests:
          - dbt_utils.accepted_range:
              arguments: {min_value: 0}
      - name: win_rate
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments: {min_value: 0, max_value: 1}
  - name: silver_masteries
    columns:
      - name: mastery_id
        tests: [not_null, unique]
      - name: puuid
        tests: [not_null]
      - name: champion_key
        tests: [not_null]
      - name: champion_points
        tests:
          - not_null
          - dbt_utils.accepted_range:
              arguments:
                min_value: 0
      - name: last_play_time
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: timestamp
          - dbt_expectations.expect_column_values_to_be_between:
              arguments:
                min_value: "2008-01-01 00:00:00"
                max_value: "2100-01-01 00:00:00"