models:
  - name: dim_players_history
    columns:
      - name: player_history_id
        tests: [not_null, unique]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments: {combination_of_columns: [puuid, valid_from]}

  - name: dim_players_current
    columns:
      - name: puuid
        tests: [not_null, unique]

  - name: fct_masteries_history
    columns:
      - name: mastery_history_id
        tests: [not_null, unique]
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments: {combination_of_columns: [puuid, champion_key, valid_from]}

  - name: fct_masteries_current
    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments: {combination_of_columns: [puuid, champion_key]}